# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, ACVector, deepseq, iterable, mmap, mtl, Octree, parallel
, QuickCheck, tagged, text, vector, zlib
}:

cabal.mkDerivation (self: {
  pname = "hPDB";
  version = "1.2.0.1";
  sha256 = "1mvfbvs94n1hlpxvk09y2kfxgkkixa315z0yq89xx7sxc6wj5gcv";
  buildDepends = [
    ACVector deepseq iterable mmap mtl Octree parallel QuickCheck
    tagged text vector zlib
  ];
  meta = {
    homepage = "https://github.com/BioHaskell/hPDB";
    description = "Protein Databank file format library";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
