# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, deepseq, deepseqGenerics, pqueue, QuickCheck }:

cabal.mkDerivation (self: {
  pname = "kdt";
  version = "0.2.2";
  sha256 = "1kj914xya5msw9hb2lqa36jf68pna8dfq21jbylq2m68k0ydcivi";
  buildDepends = [ deepseq deepseqGenerics pqueue ];
  testDepends = [ deepseq deepseqGenerics QuickCheck ];
  meta = {
    homepage = "https://github.com/giogadi/kdt";
    description = "Fast and flexible k-d trees for various types of point queries";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
