# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, ACVector, markdownUnlit, QuickCheck }:

cabal.mkDerivation (self: {
  pname = "Octree";
  version = "0.5.4.1";
  sha256 = "0pw4z29l4np1akr5s6bqdnnpalagd0giffbmacf2qpb95hisdvq0";
  buildDepends = [ ACVector QuickCheck ];
  testDepends = [ ACVector markdownUnlit QuickCheck ];
  meta = {
    homepage = "https://github.com/mgajda/octree";
    description = "Simple unbalanced Octree for storing data about 3D points";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
