# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, pretty }:

cabal.mkDerivation (self: {
  pname = "pretty-ncols";
  version = "0.1";
  sha256 = "0bvd8wgjrj9g86b1z8m9mjzswibrmhasgajnkgr2dlizl5lg7faq";
  buildDepends = [ pretty ];
  meta = {
    description = "A implementation of multi-column layout w/ Text.PrettyPrint";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
