# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, deepseq, QuickCheck }:

cabal.mkDerivation (self: {
  pname = "pretty";
  version = "1.1.2.0";
  sha256 = "043kcl2wjip51al5kx3r9qgazq5w002q520wdgdlv2c9xr74fabw";
  buildDepends = [ deepseq ];
  testDepends = [ deepseq QuickCheck ];
  meta = {
    homepage = "http://github.com/haskell/pretty";
    description = "Pretty-printing library";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
